languageCode = "en"
languageName = "English"
weight = 1
title = "Broomstick Brief"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  description = "For when rants exceed buffer limits."

[params.author]
  name = "Nina Barzh"
  email = "nina@tymyrddin.dev"
  image = "img/author.jpg"
  headline = "For when rants exceed buffer limits."
  bio = "For when rants exceed buffer limits."
