baseURL = "https://broomstick.netlify.app/"
title = "The Broomstick Brief"
theme = "github.com/adityatelange/hugo-PaperMod"
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  defaultTheme = "dark"
  ShowToc = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"