[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.search]
  enabled = true

theme = "blowfish"

[module]
  # Silence version warnings while maintaining compatibility
  hugoVersion = { min = "0.147.0", max = "0.147.99" }
