baseURL = "https://broomstick.tymyrddin.dev/"
title = "The Broomstick Brief"
theme = "github.com/adityatelange/hugo-PaperMod"
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params.assets]
  custom_css = ["css/custom.css"]

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true
  defaultTheme = "dark"
  logo = "/images/logo.png"
  logoWidth = "40"
  logoTitle = "Broomstick Brief"
  favicon = "/favicon.ico"
  custom_css = ["css/custom.css"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "tymyrddin"
    name = "Ty Myrddin"
    url = "https://tymyrddin.dev"
    weight = 20

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ninabarzh"
    weight = 30

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "saerch"
    weight = 40

[taxonomies]
  tag = "tags"
  category = "categories"