baseURL = "https://broomstick.tymyrddin.dev/"
title = "The Broomstick Brief"
theme = "github.com/adityatelange/hugo-PaperMod"
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params.assets]
  custom_css = ["css/custom.css"]
  favicon = "/favicon.ico"
  logo = "/images/logo.png"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowToc = true
  ShowShareButtons = true
  TocOpen = true
  defaultTheme = "dark"
  logoWidth = "40"
  logoTitle = "Broomstick Brief"
  custom_css = ["css/custom.css"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.1
  minMatchCharLength = 0
  # limit = 10  # Optional: Uncomment if needed
  keys = ["title", "permalink", "summary", "content"]
  # see https://www.fusejs.io/api/options.html

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "tymyrddin"
    name = "Ty Myrddin"
    url = "https://tymyrddin.dev"
    weight = 30

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ninabarzh"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "search"
    weight = 50
