baseURL = "https://broomstick.tymyrddin.dev/"
title = "The Broomstick Brief"
theme = "github.com/adityatelange/hugo-PaperMod"
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params.assets]
  custom_css = ["css/extended/custom.css"]
  favicon = "/favicon.ico"
  logo = "/images/logo.png"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowToc = true
  ShowShareButtons = true
  TocOpen = true
  defaultTheme = "dark"
  logoWidth = "40"
  logoTitle = "Broomstick Brief"
  custom_css = ["css/extended/custom.css"]
  [params.homeInfoParams]
    Title = "For when rants trigger RCU stall detection"
    Content = "and my patience buffer overflows into /dev/null. The rants are technically supposed to be brief—but let’s be real, some system bugs deserve a full kernel panic’s worth of fury."

  [[params.socialIcons]]
    name = "Mastodon"
    url = "https://mastodon.social/@barzh"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/ninabarzh"

  [[params.socialIcons]]
    name = "GitLab"
    url = "https://gitlab.com/tymyrddin"

  [[params.socialIcons]]
    name = "Move IT tube"
    url = "https://tube.spdns.org/a/barzh/video-channels"

  [[params.socialIcons]]
    name = "Website"
    url = "https://tymyrddin.dev"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.1
  minMatchCharLength = 0
  # limit = 10  # Optional: Uncomment if needed
  keys = ["title", "permalink", "summary", "content"]
  # see https://www.fusejs.io/api/options.html

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about"
    weight = 40

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "search"
    weight = 50
