[build]
  command = "hugo --gc --minify --cleanDestinationDir"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.147.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_MODULE_NPM_BINARY = "/usr/local/bin/npm"
  HUGO_MODULES_CACHE = "modules"